name: Run Tests

on:
  push:
    branches:
      - main
      - v1.x
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x, 24.x]
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - node-version: 20.x
            test-command: ci:v20
          - node-version: 22.x
            test-command: test-ci
          - node-version: 24.x
            test-command: test-ci
    name: 'Node.js ${{ matrix.node-version }} / ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore cached dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run ${{ matrix.test-command }}
